# Generated by Django 5.2.4 on 2025-08-03 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Ad Soyad')),
                ('email', models.EmailField(max_length=254, verbose_name='E-posta')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Telefon')),
                ('message', models.TextField(verbose_name='Mesaj')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Gönderim Tarihi')),
                ('is_read', models.BooleanField(default=False, verbose_name='Okundu')),
            ],
            options={
                'verbose_name': 'İletişim Mesajı',
                'verbose_name_plural': 'İletişim Mesajları',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FoodPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_code', models.CharField(max_length=50, unique=True, verbose_name='Yemek Kodu')),
                ('name', models.CharField(max_length=200, verbose_name='Yemek Adı')),
                ('current_price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Güncel Fiyat')),
                ('is_available', models.BooleanField(default=True, verbose_name='Mevcut')),
            ],
            options={
                'verbose_name': 'Yemek Fiyatı',
                'verbose_name_plural': 'Yemek Fiyatları',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MonthlyMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Menü Başlığı')),
                ('month', models.IntegerField(help_text='1=Ocak, 2=Şubat, ..., 12=Aralık', verbose_name='Ay (1-12)')),
                ('year', models.IntegerField(verbose_name='Yıl')),
                ('content', models.TextField(verbose_name='Menü İçeriği')),
                ('pdf_file', models.FileField(blank=True, upload_to='monthly_menus/', verbose_name='PDF Dosyası')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Aylık Menü',
                'verbose_name_plural': 'Aylık Menüler',
                'ordering': ['-year', '-month'],
                'unique_together': {('month', 'year')},
            },
        ),
    ]
